tasks:
  - name: "Updating Container Packages"
    init: |
      sudo apt update && sudo apt upgrade -y
      pyenv install 3.10.0
      pyenv global 3.10.0
      pip install --upgrade pip
      pip install poetry
      poetry install
    command: |
      make run
  

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# tasks:
#   - init: echo 'init script' # runs during prebuild
#     command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
