version: "3"
services:
  auth:
    image: auth_ms
    build: 
      context: .. 
      dockerfile: Dockerfile
    volumes:
      - ../auth_ms:/app
    ports:
      - 3000:8888
    command: uvicorn main:app --host=0.0.0.0 --port=8888 --reload
  