version: "3"
services:
  auth:
    image: auth_ms
    build:
      context: ..
      dockerfile: Dockerfile.test
    volumes:
      - ../auth_ms:/app/auth_ms
      - ../tests:/app/tests
    command: pytest -vv
